module.exports.restaurantNames = [
    'McDonalds',
    'Starbucks',
    'Chick-Fil-A',
    'Taco Bell',
    'Wendys',
    'Dunkin',
    'Burger King',
    'Subway',
    'Dominos',
    'Chipotle Mexican Grill',
    'Sonic',
    'Panera',
    'Pizza Hut',
    'KFC',
    'Popeyes',
    'Panda Express',
    'Dairy Queen',
    'Arbys',
    'Little Caesars',
    'Olive Garden',
    'Applebees',
    'Jack in the Box',
    'Buffalo Wild Wings',
    'Texas Roadhouse',
    'Papa Johns',
    'Chilis Bar & Grill',
    'IHOP',
    'Outback Steakhouse',
    'Dennys',
    'Draft Republic',
    'Cracker Barrel',
    'Raising Canes',
    'Red Lobster',
    'The Cheesecake Factory',
    'Wingstop',
    'Five Guys',
    'Red Robin'
]